# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-03 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EemsOnlineModels',
            fields=[
                ('id', models.TextField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
                ('extent', models.TextField(blank=True, db_column='EXTENT', null=True)),
                ('extent_gcs', models.TextField(blank=True, db_column='EXTENT_GCS', null=True)),
                ('owner', models.TextField(blank=True, db_column='OWNER', null=True)),
                ('short_description', models.TextField(blank=True, db_column='SHORT_DESCRIPTION', null=True)),
                ('long_description', models.TextField(blank=True, db_column='LONG_DESCRIPTION', null=True)),
                ('author', models.TextField(blank=True, db_column='AUTHOR', null=True)),
                ('creation_date', models.TextField(blank=True, db_column='CREATION_DATE', null=True)),
                ('epsg', models.TextField(blank=True, db_column='EPSG', null=True)),
                ('project', models.TextField(blank=True, db_column='PROJECT', null=True)),
                ('user', models.TextField(blank=True, db_column='USER', null=True)),
                ('status', models.TextField(blank=True, db_column='STATUS', null=True)),
                ('upload_datetime', models.TextField(blank=True, db_column='UPLOAD_DATETIME', null=True)),
            ],
            options={
                'db_table': 'EEMS_ONLINE_MODELS',
                'managed': True,
            },
        ),
    ]
