# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-03 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eems_online_app', '0002_auto_20170803_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eemsonlinemodels',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'managed': True, 'permissions': (('view_task', 'View task'),)},
        ),
    ]
